
networks:
  service:
    name: benutzerverwaltung-service-main
  architecture:
    name: main

services:
  rest-api-benutzerverwaltung1:
    container_name: rest-api-benutzerverwaltung1
    build: rest_api
    ports:
      - "8000:8000"
    networks:
      - service
      - architecture

  db-benutzerverwaltung1:
    build: datenbank
    container_name: db-benutzerverwaltung1
    ports:
      - "5432:5432"
    networks:
      - service
    environment:
      POSTGRES_PASSWORD: test
      network-alias: db-benutzerverwaltung1